#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on 2016-06-24 ... */ 
#define XMLRPC_C_VERSION "1.39.8" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 39 
#define XMLRPC_VERSION_POINT 8 
#endif 
